### ISSUE TITLE
Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by Snouffle** [Tenderly/hardhat-tenderly#187]
When running `yarn private:calculator:automatic` in [ethers-v6 example
](https://github.com/Tenderly/hardhat-tenderly/tree/master/examples/contract-verification/ethers-v6)

Doesn't work in [ethers-v5 example
](https://github.com/Tenderly/hardhat-tenderly/tree/master/examples/contract-verification/ethers-v5) as well

Currently on macOS Ventura 13.6.6 
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:750:18)
    at tryReadSync (node:fs:424:20)
    at Object.readFileSync (node:fs:478:19)
    at getConfig (/Users/snouffle/hardhat-tenderly/examples/contract-verification/ethers-v6/node_modules/@tenderly/hardhat-tenderly/node_modules/tenderly/src/utils/config.ts:15:25)
    at new TenderlyNetwork (/Users/snouffle/hardhat-tenderly/examples/contract-verification/ethers-v6/node_modules/@tenderly/hardhat-tenderly/src/TenderlyNetwork.ts:42:39)
    at new Tenderly (/Users/snouffle/hardhat-tenderly/examples/contract-verification/ethers-v6/node_modules/@tenderly/hardhat-tenderly/src/Tenderly.ts:42:28)
    at /Users/snouffle/hardhat-tenderly/examples/contract-verification/ethers-v6/node_modules/@tenderly/hardhat-tenderly/src/tenderly/extender.ts:45:37
    at getRealTarget (/Users/snouffle/hardhat-tenderly/examples/contract-verification/ethers-v6/node_modules/hardhat/src/internal/util/lazy.ts:112:22)
    at Object.get (/Users/snouffle/hardhat-tenderly/examples/contract-verification/ethers-v6/node_modules/hardhat/src/internal/util/lazy.ts:185:26)
    at TdlyContract._tdlyVerify (/Users/snouffle/hardhat-tenderly/examples/contract-verification/ethers-v6/node_modules/@tenderly/hardhat-tenderly/src/tenderly/ethers/Contract.ts:94:25) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

I have tried to use sudo but same behavior

<img width="487" alt="screenshot" src="https://github.com/Tenderly/hardhat-tenderly/assets/165510887/8447a48f-6b23-4900-bb42-8e7bae56394e">

I found out that `@tenderly/hardhat-tenderly` **DOESN'T HAVE A SRC FOLDER** so when hardhat tries to read it, it doesn't work

I don't know if it's related but when I am running `tenderly login`

I type my accesskey and they I get this **error**: `Couldn't write global config file` if I do this command in sudo, I can login but it doesn't work either way

**Comment by Snouffle** [comment]
Problem fixed I had to delete my ~/.tenderly folder and it worked 👍👍👍🥳🥳🥳🥳
