### ISSUE TITLE
`Error: Cannot find module 'tenderly'`

### ISSUE THREAD

**Issue by pcaversaccio** [Tenderly/hardhat-tenderly#84]
After upgrading from `1.1.6` to `1.3.0` (the same would happen actually for `1.2.0`) I get the following error while running `npx hardhat test` for instance. You can reproduce the error via this [repo](https://github.com/pcaversaccio/hardhat-project-template-ts). 

```bash
An unexpected error occurred:

Error: Cannot find module 'tenderly'
Require stack:
- /home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/@tenderly/hardhat-tenderly/dist/tasks/push.js
- /home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/@tenderly/hardhat-tenderly/dist/tasks/index.js
- /home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/@tenderly/hardhat-tenderly/dist/index.js
- /home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/hardhat.config.ts
- /home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/hardhat/internal/core/config/config-loading.js
- /home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:833:2[7](https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/3392508036/jobs/5638790968#step:8:8))
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:1[8](https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/3392508036/jobs/5638790968#step:8:9))
    at Object.<anonymous> (/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/@tenderly/hardhat-tenderly/src/tasks/push.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:120[9](https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/3392508036/jobs/5638790968#step:8:10):[10](https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/3392508036/jobs/5638790968#step:8:11))
    at Object.require.extensions.<computed> [as .js] (/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/ts-node/src/index.ts:[16](https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/3392508036/jobs/5638790968#step:8:17)08:43)
    at Module.load (node:internal/modules/cjs/loader:1033:[32](https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/3392508036/jobs/5638790968#step:8:33)) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/@tenderly/hardhat-tenderly/dist/tasks/push.js',
    '/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/@tenderly/hardhat-tenderly/dist/tasks/index.js',
    '/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/@tenderly/hardhat-tenderly/dist/index.js',
    '/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/hardhat.config.ts',
    '/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/hardhat/internal/core/config/config-loading.js',
    '/home/runner/work/hardhat-project-template-ts/hardhat-project-template-ts/node_modules/hardhat/internal/cli/cli.js'
  ]
}
```

> The above error is from a GitHub action: https://github.com/pcaversaccio/hardhat-project-template-ts/actions/runs/3392508036/jobs/5638790968.

The error stems from calling `tdly.setup({ automaticVerifications: false });` in the [`hardhat.config.ts`](https://github.com/pcaversaccio/hardhat-project-template-ts/blob/main/hardhat.config.ts#L18). If you disable it completely, everything works smooth. So I guess, your refactor added a regression somehow.

In the meantime I downgraded again to `1.1.6` and it works fine.

**Comment by pcaversaccio** [comment]
Please check this @Riphal.

**Comment by Riphal** [comment]
Sorry for the late reply, I was away for a few days. I'll start looking into this now and let you know when it's fixed.

**Comment by pcaversaccio** [comment]
awesome - let me know if you need further logs or information

**Comment by Riphal** [comment]
@pcaversaccio the fix is published, please fetch `@tenderly/hardhat-tenderly` latest version and try again it should work now.

**Comment by pcaversaccio** [comment]
Ok it works - a small addendum, could you upgrade the in `tenderly` the `got` deps at some point?

I got the following alert.
```
@tenderly/hardhat-tenderly@1.3.1 requires got@11.8.3 via a transitive dependency on tenderly@0.0.2
```

![image](https://user-images.githubusercontent.com/25297591/200543209-ebce0357-2674-472d-a447-e329f149e538.png)

**Comment by Riphal** [comment]
Yes, it is not used I just forgot to delete it from dependencies I will release a new version now so you don't get that error anymore.

**Comment by Riphal** [comment]
I released a new version. Please fetch `@tenderly/hardhat-tenderly` latest version again.
It should remove the dependencybot error.

**Comment by pcaversaccio** [comment]
confirmed @Riphal - thx for fixing the issues.
